// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlR5MfoVOfZWXF2j9vzmIroC_Tv65dek',
    appId: '1:325204551736:web:02996f9e4be6ce08f29ecd',
    messagingSenderId: '325204551736',
    projectId: 'travel-trek-25d21',
    authDomain: 'travel-trek-25d21.firebaseapp.com',
    storageBucket: 'travel-trek-25d21.firebasestorage.app',
    measurementId: 'G-CM0057T96Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXxQ4CusVEKFtDs46-G__ybAF57vKF1I',
    appId: '1:325204551736:android:3458387c46df7bd0f29ecd',
    messagingSenderId: '325204551736',
    projectId: 'travel-trek-25d21',
    storageBucket: 'travel-trek-25d21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3JAuYmE7HOc0moRghsN3V0fizbu_05Q',
    appId: '1:325204551736:ios:99908addbf357b74f29ecd',
    messagingSenderId: '325204551736',
    projectId: 'travel-trek-25d21',
    storageBucket: 'travel-trek-25d21.firebasestorage.app',
    iosBundleId: 'com.example.travelTrek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3JAuYmE7HOc0moRghsN3V0fizbu_05Q',
    appId: '1:325204551736:ios:99908addbf357b74f29ecd',
    messagingSenderId: '325204551736',
    projectId: 'travel-trek-25d21',
    storageBucket: 'travel-trek-25d21.firebasestorage.app',
    iosBundleId: 'com.example.travelTrek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzlR5MfoVOfZWXF2j9vzmIroC_Tv65dek',
    appId: '1:325204551736:web:be76ec5f12e978c7f29ecd',
    messagingSenderId: '325204551736',
    projectId: 'travel-trek-25d21',
    authDomain: 'travel-trek-25d21.firebaseapp.com',
    storageBucket: 'travel-trek-25d21.firebasestorage.app',
    measurementId: 'G-158G2VL4PX',
  );
}
